language: node_js
node_js:
  - "8"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=CI PORT=3000
cache:
  directories:
    - node_modules
    - web-app/node_modules
install:
  - npm install
  - npm run build
before_script: cd web-app  
script:
  - nohup npm run start &
  - sleep 3
  - npm run test